name: Build sitemap.json

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate sitemap.json
        run: |
          python3 - << 'PY'
          import os, json

          folders = [d for d in os.listdir(".") if os.path.isdir(d) and not d.startswith(".")]
          folders.sort(key=str.lower)

          site = {}
          for d in folders:
            files = [f for f in os.listdir(d) if f.lower().endswith(".html")]
            files.sort(key=str.lower)
            site[d] = files

          with open("sitemap.json", "w", encoding="utf-8") as f:
            json.dump(site, f, ensure_ascii=False, indent=2)
          PY

      - name: Commit sitemap.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.json
          git commit -m "Auto-generate sitemap.json" || exit 0
          git push
